services:
  userservice:
    build:
      context: ./src/userservice
    environment:
      - GRPC_PORT=50051
      - POSTGRES_URL=postgres://postgres:postgres@userservice_db:5432/userdb?sslmode=disable
      - JWT_SECRET=SomeHardAndSecretWord
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=GonaGona
      - MINIO_BUCKET=avatars
      - MINIO_PUBLIC_ENDPOINT=http://localhost:9200
    depends_on:
      - userservice_db
    ports:
      - "50051:50051"
    networks:
      - app-network

  gateway:
    build:
      context: ./src/gateway
    environment:
      - USERSERVICE_ADDR=userservice:50051
      - GATEWAY_HTTP_PORT=8080
    depends_on:
      - userservice
    ports:
      - "8080:8080"
    networks:
      - app-network 
    restart: unless-stopped

  supportchat:
    build:
      context: ./src/supportchat
    ports:
      - "9100:9000"
    environment:
      - REDIS_ADDR=redis:6379
      - SUPPORTCHAT_PORT=9000
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  userservice_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  productcatalog_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9200:9000" 
      - "9201:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: GonaGona
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    restart: unless-stopped

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin GonaGona &&
      mc mb -p local/avatars || true &&
      mc anonymous set download local/avatars
      "
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    volumes:
      - ./src/userservice/migrations:/migrations
    entrypoint: >
      sh -c "
      until nc -z userservice_db 5432; do
        echo 'Waiting for Postgres...';
        sleep 2;
      done &&
      migrate -path=/migrations -database postgres://postgres:postgres@userservice_db:5432/userdb?sslmode=disable up
      "
    depends_on:
      - userservice_db
    networks:
      - app-network

networks:
  app-network:

volumes:
  minio-data: