name: Docker Build for All Services

on:
  push:
    paths:
      - "src/**/Dockerfile"
      - "src/**/**.go"
  pull_request:
    paths:
      - "src/**/Dockerfile"
      - "src/**/**.go"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images for all services
        run: |
          for service in ./src/*/ ; do
            if [ -f "$service/Dockerfile" ]; then
              echo "Building Docker image for $service"
              docker build -t test-$(basename $service):latest $service || exit 1
            fi
          done
